package webservice.calculadora;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-28T10:54:39.543+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "CalculadoraSoapImplService", 
                  wsdlLocation = "http://localhost:8080/ejercicio1/service/CalculadoraSoap?wsdl",
                  targetNamespace = "calculadora.webservice") 
public class CalculadoraSoapImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("calculadora.webservice", "CalculadoraSoapImplService");
    public final static QName CalculadoraSoapImplPort = new QName("calculadora.webservice", "CalculadoraSoapImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ejercicio1/service/CalculadoraSoap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculadoraSoapImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ejercicio1/service/CalculadoraSoap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculadoraSoapImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculadoraSoapImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraSoapImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CalculadoraSoapImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculadoraSoapImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculadoraSoapImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CalculadoraSoapImpl
     */
    @WebEndpoint(name = "CalculadoraSoapImplPort")
    public CalculadoraSoapImpl getCalculadoraSoapImplPort() {
        return super.getPort(CalculadoraSoapImplPort, CalculadoraSoapImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadoraSoapImpl
     */
    @WebEndpoint(name = "CalculadoraSoapImplPort")
    public CalculadoraSoapImpl getCalculadoraSoapImplPort(WebServiceFeature... features) {
        return super.getPort(CalculadoraSoapImplPort, CalculadoraSoapImpl.class, features);
    }

}
