package webservice.calculadora;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-28T10:54:39.537+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "calculadora.webservice", name = "CalculadoraSoapImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculadoraSoapImpl {

    @WebMethod
    @RequestWrapper(localName = "multiplicar", targetNamespace = "calculadora.webservice", className = "webservice.calculadora.Multiplicar")
    @ResponseWrapper(localName = "multiplicarResponse", targetNamespace = "calculadora.webservice", className = "webservice.calculadora.MultiplicarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public float multiplicar(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1
    );

    @WebMethod
    @RequestWrapper(localName = "dividir", targetNamespace = "calculadora.webservice", className = "webservice.calculadora.Dividir")
    @ResponseWrapper(localName = "dividirResponse", targetNamespace = "calculadora.webservice", className = "webservice.calculadora.DividirResponse")
    @WebResult(name = "return", targetNamespace = "")
    public float dividir(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1
    );

    @WebMethod
    @RequestWrapper(localName = "sum", targetNamespace = "calculadora.webservice", className = "webservice.calculadora.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "calculadora.webservice", className = "webservice.calculadora.SumResponse")
    @WebResult(name = "return", targetNamespace = "")
    public float sum(
        @WebParam(name = "a", targetNamespace = "")
        float a,
        @WebParam(name = "b", targetNamespace = "")
        float b
    );
}
