package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-28T09:49:02.699+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://webservice/", name = "HolaMundoSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface HolaMundoSoap {

    @WebMethod
    @RequestWrapper(localName = "despedir", targetNamespace = "http://webservice/", className = "webservice.Despedir")
    @ResponseWrapper(localName = "despedirResponse", targetNamespace = "http://webservice/", className = "webservice.DespedirResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String despedir(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "saludar", targetNamespace = "http://webservice/", className = "webservice.Saludar")
    @ResponseWrapper(localName = "saludarResponse", targetNamespace = "http://webservice/", className = "webservice.SaludarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String saludar(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
