package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-28T09:49:02.704+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "HolaMundoSoapImplService", 
                  wsdlLocation = "http://localhost:8080/basico/service/HolaMundoSoap?wsdl",
                  targetNamespace = "http://webservice/") 
public class HolaMundoSoapImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice/", "HolaMundoSoapImplService");
    public final static QName HolaMundoSoapImplPort = new QName("http://webservice/", "HolaMundoSoapImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/basico/service/HolaMundoSoap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HolaMundoSoapImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/basico/service/HolaMundoSoap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HolaMundoSoapImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HolaMundoSoapImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HolaMundoSoapImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HolaMundoSoapImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HolaMundoSoapImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HolaMundoSoapImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HolaMundoSoap
     */
    @WebEndpoint(name = "HolaMundoSoapImplPort")
    public HolaMundoSoap getHolaMundoSoapImplPort() {
        return super.getPort(HolaMundoSoapImplPort, HolaMundoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolaMundoSoap
     */
    @WebEndpoint(name = "HolaMundoSoapImplPort")
    public HolaMundoSoap getHolaMundoSoapImplPort(WebServiceFeature... features) {
        return super.getPort(HolaMundoSoapImplPort, HolaMundoSoap.class, features);
    }

}
