
package webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-28T09:49:02.642+02:00
 * Generated source version: 3.1.0
 * 
 */
public final class HolaMundoSoap_HolaMundoSoapImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice/", "HolaMundoSoapImplService");

    private HolaMundoSoap_HolaMundoSoapImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HolaMundoSoapImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HolaMundoSoapImplService ss = new HolaMundoSoapImplService(wsdlURL, SERVICE_NAME);
        HolaMundoSoap port = ss.getHolaMundoSoapImplPort();  
        
        {
        System.out.println("Invoking despedir...");
        java.lang.String _despedir_arg0 = "";
        java.lang.String _despedir__return = port.despedir(_despedir_arg0);
        System.out.println("despedir.result=" + _despedir__return);


        }
        {
        System.out.println("Invoking saludar...");
        java.lang.String _saludar_arg0 = "";
        java.lang.String _saludar__return = port.saludar(_saludar_arg0);
        System.out.println("saludar.result=" + _saludar__return);


        }

        System.exit(0);
    }

}
