package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-29T11:26:21.574+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "PersonSoap", 
                  wsdlLocation = "http://localhost:8080/ejercicio2/service/PersonSoap?wsdl",
                  targetNamespace = "http://webservice/") 
public class PersonSoap extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice/", "PersonSoap");
    public final static QName PersonaSoapPort = new QName("http://webservice/", "PersonaSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ejercicio2/service/PersonSoap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonSoap.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ejercicio2/service/PersonSoap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonSoap(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonSoap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonSoap() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PersonSoap(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PersonSoap(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PersonSoap(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PersonaSoap
     */
    @WebEndpoint(name = "PersonaSoapPort")
    public PersonaSoap getPersonaSoapPort() {
        return super.getPort(PersonaSoapPort, PersonaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonaSoap
     */
    @WebEndpoint(name = "PersonaSoapPort")
    public PersonaSoap getPersonaSoapPort(WebServiceFeature... features) {
        return super.getPort(PersonaSoapPort, PersonaSoap.class, features);
    }

}
