package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-29T11:26:21.565+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://webservice/", name = "PersonaSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonaSoap {

    @WebMethod
    @RequestWrapper(localName = "findPerson", targetNamespace = "http://webservice/", className = "webservice.FindPerson")
    @ResponseWrapper(localName = "findPersonResponse", targetNamespace = "http://webservice/", className = "webservice.FindPersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public webservice.Person findPerson(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Integer id
    );

    @WebMethod
    @RequestWrapper(localName = "removePerson", targetNamespace = "http://webservice/", className = "webservice.RemovePerson")
    @ResponseWrapper(localName = "removePersonResponse", targetNamespace = "http://webservice/", className = "webservice.RemovePersonResponse")
    public void removePerson(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Integer id
    );

    @WebMethod
    @RequestWrapper(localName = "findPersons", targetNamespace = "http://webservice/", className = "webservice.FindPersons")
    @ResponseWrapper(localName = "findPersonsResponse", targetNamespace = "http://webservice/", className = "webservice.FindPersonsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<webservice.Person> findPersons();

    @WebMethod
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://webservice/", className = "webservice.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://webservice/", className = "webservice.AddPersonResponse")
    public void addPerson(
        @WebParam(name = "person", targetNamespace = "")
        webservice.Person person
    );

    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://webservice/", className = "webservice.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://webservice/", className = "webservice.UpdatePersonResponse")
    public void updatePerson(
        @WebParam(name = "person", targetNamespace = "")
        webservice.Person person
    );
}
