
package webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-29T11:26:21.496+02:00
 * Generated source version: 3.1.0
 * 
 */
public final class PersonaSoap_PersonaSoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice/", "PersonSoap");

    private PersonaSoap_PersonaSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PersonSoap.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PersonSoap ss = new PersonSoap(wsdlURL, SERVICE_NAME);
        PersonaSoap port = ss.getPersonaSoapPort();  
        
        {
        System.out.println("Invoking findPerson...");
        java.lang.Integer _findPerson_id = null;
        webservice.Person _findPerson__return = port.findPerson(_findPerson_id);
        System.out.println("findPerson.result=" + _findPerson__return);


        }
        {
        System.out.println("Invoking removePerson...");
        java.lang.Integer _removePerson_id = null;
        port.removePerson(_removePerson_id);


        }
        {
        System.out.println("Invoking findPersons...");
        java.util.List<webservice.Person> _findPersons__return = port.findPersons();
        System.out.println("findPersons.result=" + _findPersons__return);


        }
        {
        System.out.println("Invoking addPerson...");
        webservice.Person _addPerson_person = null;
        port.addPerson(_addPerson_person);


        }
        {
        System.out.println("Invoking updatePerson...");
        webservice.Person _updatePerson_person = null;
        port.updatePerson(_updatePerson_person);


        }

        System.exit(0);
    }

}
